version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "bower.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: dependency-cache-{{ checksum "bower.json" }}
          paths:
            - bower_components*
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm test
      - run: npm run test:integration

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
